### ISSUE TITLE
在windows平台上运行出错, 好像包导入有问题

### ISSUE THREAD

**Issue by 26903651** [PaddlePaddle/Parakeet#101]
Windows 10环境
python : 3.8.8
pip : 21.0.1
paddle-parakeet : 0.2.0b3

以下是运行时的报错信息

C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\pip\_vendor\packaging\version.py:127: DeprecationWarning: Creating a LegacyVersion has been deprecated and will be removed in the next major release
  warnings.warn(
C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\pip\_vendor\packaging\version.py:127: DeprecationWarning: Creating a LegacyVersion has been deprecated and will be removed in the next major release
  warnings.warn(
[2021-03-26 09:02:02,392] [ WARNING] - An error was encountered while loading deepvoice3_ljspeech. Detailed error information can be found in the C:\Users\Administrator\.paddlehub\log\20210326.log.
[2021-03-26 09:02:02,398] [ WARNING] - An error was encountered while loading deepvoice3_ljspeech. Detailed error information can be found in the C:\Users\Administrator\.paddlehub\log\20210326.log.
Download https://bj.bcebos.com/paddlehub/paddlehub_dev/deepvoice3_ljspeech.tar.gz
[##################################################] 100.00%
Decompress C:\Users\Administrator\.paddlehub\tmp\tmpgjuaz693\deepvoice3_ljspeech.tar.gz
[##################################################] 100.00%[2021-03-26 09:02:21,433] [    INFO] - Successfully uninstalled deepvoice3_ljspeech

Traceback (most recent call last):
  File "test03.py", line 10, in <module>
    module = hub.Module(name="deepvoice3_ljspeech")
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\paddlehub\module\module.py", line 171, in __new__
    module = cls.init_with_name(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\paddlehub\module\module.py", line 263, in init_with_name
    user_module_cls = manager.install(name=name, version=version, source=source, update=update, branch=branch)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\paddlehub\module\manager.py", line 188, in install
    return self._install_from_name(name, version)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\paddlehub\module\manager.py", line 263, in _install_from_name
    return self._install_from_url(item['url'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\paddlehub\module\manager.py", line 256, in _install_from_url
    return self._install_from_archive(file)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\paddlehub\module\manager.py", line 361, in _install_from_archive
    return self._install_from_directory(directory)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\paddlehub\module\manager.py", line 345, in _install_from_directory
    hub_module_cls = HubModule.load(self._get_normalized_path(module_info.name))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\paddlehub\module\module.py", line 195, in load
    py_module = utils.load_py_module(dirname, '{}.module'.format(basename))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\paddlehub\utils\utils.py", line 249, in load_py_module
    py_module = importlib.import_module(py_module_name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Administrator\.paddlehub\modules\deepvoice3_ljspeech\module.py", line 59, in <module>
    from parakeet.utils import io
ImportError: cannot import name 'io' from 'parakeet.utils' (C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\parakeet\utils\__init__.py)

**Comment by 26903651** [comment]
我在一台新机器上试了一下，同样的报错，很容易复现，没有人和我是同样问题吗？

**Comment by iclementine** [comment]
deepvoice3_ljspeech 这个应该是较早的版本了（切换到 release/v0.1 分支，然后使用 paddle 1.8.5 版本应该可以使用），我们目前还没有升级这个模型到新版本来。
