### ISSUE TITLE
24773 wav file(s) were ignored because neither a .lab file or a .TextGrid file could be found

### ISSUE THREAD

**Issue by lgf821793883** [PaddlePaddle/Parakeet#113]
Setting up corpus information...
24773 wav file(s) were ignored because neither a .lab file or a .TextGrid file could be found, please see C:\Users\xiaofeng/Documents/MFA\test\logging\corpus.log for more information
set()
Traceback (most recent call last):
  File "aligner\command_line\train_and_align.py", line 171, in <module>
  File "aligner\command_line\train_and_align.py", line 53, in align_corpus
  File "aligner\dictionary.py", line 128, in __init__
  File "aligner\dictionary.py", line 18, in compile_graphemes
  File "C:\Users\micha\Miniconda3\envs\aligner\lib\re.py", line 233, in compile
  File "C:\Users\micha\Miniconda3\envs\aligner\lib\re.py", line 301, in _compile
  File "C:\Users\micha\Miniconda3\envs\aligner\lib\sre_compile.py", line 562, in compile
  File "C:\Users\micha\Miniconda3\envs\aligner\lib\sre_parse.py", line 855, in parse
  File "C:\Users\micha\Miniconda3\envs\aligner\lib\sre_parse.py", line 416, in _parse_sub
  File "C:\Users\micha\Miniconda3\envs\aligner\lib\sre_parse.py", line 765, in _parse
  File "C:\Users\micha\Miniconda3\envs\aligner\lib\sre_parse.py", line 416, in _parse_sub
  File "C:\Users\micha\Miniconda3\envs\aligner\lib\sre_parse.py", line 523, in _parse
sre_constants.error: unterminated character set at position 5
[3104] Failed to execute script train_and_align

在处理音频时出现以下错误，请问a.lab file 和 a .TextGrid file 是怎么来的，这里执行不下去了，还望大佬指教。

**Comment by lgf821793883** [comment]
在执行Tacotron2 + AISHELL-3 数据集训练语音克隆模型  音频处理时，发生
准备好之后运行训练和对齐。首先下载 Montreal Force Aligner 1.0.下载之后解压即可运行。cd 到其中的 bin 文件夹运行命令，即可进行训练和对齐。前三个命令行参数分别是音频文件夹的路径，词典路径和对齐文件输出路径。可以通过-o 传入训练得到的模型保存路径。

./mfa_train_and_align \
  ~/datasets/aishell3/train/wav \   我传入了一些wav文件
  lexicon.txt \                                  词典
  ~/datasets/aishell3/train/alignment \   输出路径
  -o aishell3_model \ 
  -v

**Comment by iclementine** [comment]
一般我们使用如下的流程：

准备好一个存放了音频文件的文件夹。而且每个音频文件都有一个同名的 .lab 文件和它存放在同一文件夹。

```text
+-- prosodylab_corpus_directory
|   +-- speaker1
|           --- recording1.wav
|           --- recording1.lab
|           --- recording2.wav
|           --- recording2.lab
|   +-- speaker2
|           --- recording3.wav
|           --- recording3.lab
|       --- ...
```

类似这样子。然后 `*.lab` 文件是自己抽取 Prosody 里面的拼音标注的。比如说对于第一个句子，抽取的结果就是 

```text
ka2 er2 pu3 pei2 wai4 sun1 wan2 hua2 ti
```

这是一个没有时长的整句标注。（当然 *.lab 文件也可以有时长标记的啦。但是我们这里这个 lab 文件就是用来给 MFA 作为整句标注之用。）

然后词典是类似

```tetx
ka2 k a2
er2 er2
pu3 p u3
```
这样的文件。（可以类比英语， *lab 文件中按空格分割就是单词， lexicon 里面需要保证每个词都有对应的转写规则。我们这里事实上就是音节-> 声母 + 韵母和声调 的词典。并不是真正的汉字到声母韵母的词典）

然后 TextGrid 文件就会输出在 output 文件夹，这个文件夹会和输入文件夹保持同构。

所以你需要做的就是从文本标注那里抽取拼音标注，然后存成和音频同名的 *.lab 文件就可以。
