### ISSUE TITLE
训练example里的transformer_tts报错

### ISSUE THREAD

**Issue by ymzlygw** [PaddlePaddle/Parakeet#18]
我按照步骤想训练example里面的transformer_tts模型。环境和clone库都已经准备好，LJSpeech数据也下载准备好。但是在命令行输入运行函数和传入参数后，却报错如下：
**运行命令：**python train_transformer.py \
--use_gpu=1 \
--data='~/datasets/LJSpeech-1.1'  \
--output='./experiments'  \
--config='configs/ljspeech.yaml'  \

**报错log**：**

{'checkpoint': None,
 'config': 'configs/ljspeech.yaml',
 'data': '~/datasets/LJSpeech-1.1',
 'iteration': None,
 'output': './experiment',
 'use_gpu': 1}
W0701 01:08:32.058022 15717 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 10.1, Runtime API Version: 10.0
W0701 01:08:32.060909 15717 device_context.cc:260] device: 0, cuDNN Version: 7.6.
Rank 0: checkpoint loaded.
0it [00:00, ?it/s]/root/anaconda3/envs/paddle/lib/python3.7/site-packages/librosa/core/audio.py:161: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn('PySoundFile failed. Trying audioread instead.')
2020-07-01 01:08:36,171-WARNING: DygraphDataLoader reader thread raised an exception.
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/root/anaconda3/envs/paddle/lib/python3.7/site-packages/librosa/core/audio.py", line 129, in load
    with sf.SoundFile(path) as sf_desc:
  File "/root/anaconda3/envs/paddle/lib/python3.7/site-packages/soundfile.py", line 629, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "/root/anaconda3/envs/paddle/lib/python3.7/site-packages/soundfile.py", line 1184, in _open
    "Error opening {0!r}: ".format(self.name))
  File "/root/anaconda3/envs/paddle/lib/python3.7/site-packages/soundfile.py", line 1357, in _error_check
    raise RuntimeError(prefix + _ffi.string(err_str).decode('utf-8', 'replace'))
RuntimeError: Error opening '~/datasets/LJSpeech-1.1/wavs/LJ019-0253.wav': System error.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/envs/paddle/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/root/anaconda3/envs/paddle/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/root/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/reader.py", line 913, in _reader_thread_loop_for_singleprocess
    six.reraise(*sys.exc_info())
  File "/root/anaconda3/envs/paddle/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/root/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/reader.py", line 892, in _reader_thread_loop_for_singleprocess
    for sample in self._batch_reader():
  File "/root/AI_/Paddle/Parakeet/parakeet/data/datacargo.py", line 112, in __next__
    minibatch = [self._dataset[i] for i in index]
  File "/root/AI_/Paddle/Parakeet/parakeet/data/datacargo.py", line 112, in <listcomp>
    minibatch = [self._dataset[i] for i in index]
  File "/root/AI_/Paddle/Parakeet/parakeet/data/dataset.py", line 47, in __getitem__
    return self.get_example(index)
  File "/root/AI_/Paddle/Parakeet/parakeet/data/dataset.py", line 100, in get_example
    self._cache[i] = self._dataset[i]
  File "/root/AI_/Paddle/Parakeet/parakeet/data/dataset.py", line 47, in __getitem__
    return self.get_example(index)
  File "/root/AI_/Paddle/Parakeet/parakeet/data/dataset.py", line 82, in get_example
    return self._transform(in_data)
  File "/root/AI_/Paddle/Parakeet/examples/transformer_tts/data.py", line 119, in __call__
    wav, _ = librosa.load(str(fname))
  File "/root/anaconda3/envs/paddle/lib/python3.7/site-packages/librosa/core/audio.py", line 162, in load
    y, sr_native = __audioread_load(path, offset, duration, dtype)
  File "/root/anaconda3/envs/paddle/lib/python3.7/site-packages/librosa/core/audio.py", line 186, in __audioread_load
    with audioread.audio_open(path) as input_file:
  File "/root/anaconda3/envs/paddle/lib/python3.7/site-packages/audioread/__init__.py", line 111, in audio_open
    return BackendClass(path)
  File "/root/anaconda3/envs/paddle/lib/python3.7/site-packages/audioread/rawread.py", line 62, in __init__
    self._fh = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '~/datasets/LJSpeech-1.1/wavs/LJ019-0253.wav'

Traceback (most recent call last):
  File "train_transformer.py", line 217, in <module>
    main(args)
  File "train_transformer.py", line 113, in main
    batch = next(iterator)
  File "/root/anaconda3/envs/paddle/lib/python3.7/site-packages/tqdm/_tqdm.py", line 897, in __iter__
    for obj in iterable:
  File "/root/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/reader.py", line 804, in __next__
    return self._reader.read_next_var_list()
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::operators::reader::BlockingQueue<std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> > >::Receive(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
3   paddle::operators::reader::PyReader::ReadNext(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
4   std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<unsigned long>, std::__future_base::_Result_base::_Deleter>, unsigned long> >::_M_invoke(std::_Any_data const&)
5   std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&)
6   ThreadPool::ThreadPool(unsigned long)::{lambda()#1}::operator()() const

----------------------
Error Message Summary:
----------------------
Error: Blocking queue is killed because the data reader raises an exception
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] at (/paddle/paddle/fluid/operators/reader/blocking_queue.h:141)

这是什么原因呢？希望开发人员帮忙解决，谢谢

**Comment by lfchener** [comment]
![image](https://user-images.githubusercontent.com/6771821/86193609-f04be300-bb7e-11ea-915a-00d8ee10e048.png)
看报错是文件不存在，请确认一下文件路径。

**Comment by ymzlygw** [comment]
> ![image](https://user-images.githubusercontent.com/6771821/86193609-f04be300-bb7e-11ea-915a-00d8ee10e048.png)
> 看报错是文件不存在，请确认一下文件路径。

这个文件是存在的，我在数据集里面找到了这个文件。并且这块报错的不存在文件名每次都是不一样的，每次我查看数据集都是完整的的，index都是连续的，不存在缺文件的情况。

**Comment by ymzlygw** [comment]
> ![image](https://user-images.githubusercontent.com/6771821/86193609-f04be300-bb7e-11ea-915a-00d8ee10e048.png)
> 看报错是文件不存在，请确认一下文件路径。

我感觉是datareader的部分可能有问题？数据集我下载了解压替换了两遍，数据集本身应该不会出问题才对，但是每次运行都会选出一个数据说这个数据不存在，可是查找又能找到数据，数据集本身是完整的。

**Comment by ymzlygw** [comment]
> ![image](https://user-images.githubusercontent.com/6771821/86193609-f04be300-bb7e-11ea-915a-00d8ee10e048.png)
> 看报错是文件不存在，请确认一下文件路径。

你好，自己又弄了好久。发现是自己数据集路径的写法不规范造成的，感谢你的回答~
