### ISSUE TITLE
ImportError: The module requires additional dependencies: ruamel.

### ISSUE THREAD

**Issue by a112121788** [PaddlePaddle/Parakeet#202]
ImportError: The module requires additional dependencies: ruamel. You can install parakeet via 'git clone https://github.com/PaddlePaddle/Parakeet && cd Parakeet && pip install -e .' and others via pip install

```bash
Traceback (most recent call last):
  File "/miniconda/bin/hub", line 8, in <module>
    sys.exit(execute())
  File "/miniconda/lib/python3.8/site-packages/paddlehub/commands/utils.py", line 78, in execute
    status = 0 if com['_entry']().execute(sys.argv[idx:]) else 1
  File "/miniconda/lib/python3.8/site-packages/paddlehub/commands/install.py", line 55, in execute
    manager.install(name=name, version=version, ignore_env_mismatch=args.ignore_env_mismatch)
  File "/miniconda/lib/python3.8/site-packages/paddlehub/module/manager.py", line 190, in install
    return self._install_from_name(name, version, ignore_env_mismatch)
  File "/miniconda/lib/python3.8/site-packages/paddlehub/module/manager.py", line 265, in _install_from_name
    return self._install_from_url(item['url'])
  File "/miniconda/lib/python3.8/site-packages/paddlehub/module/manager.py", line 258, in _install_from_url
    return self._install_from_archive(file)
  File "/miniconda/lib/python3.8/site-packages/paddlehub/module/manager.py", line 380, in _install_from_archive
    return self._install_from_directory(directory)
  File "/miniconda/lib/python3.8/site-packages/paddlehub/module/manager.py", line 364, in _install_from_directory
    hub_module_cls = HubModule.load(self._get_normalized_path(module_info.name))
  File "/miniconda/lib/python3.8/site-packages/paddlehub/module/module.py", line 418, in load
    py_module = utils.load_py_module(dirname, '{}.module'.format(basename))
  File "/miniconda/lib/python3.8/site-packages/paddlehub/utils/utils.py", line 250, in load_py_module
    py_module = importlib.import_module(py_module_name)
  File "/miniconda/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/.paddlehub/modules/deepvoice3_ljspeech/module.py", line 65, in <module>
    raise ImportError(
ImportError: The module requires additional dependencies: ruamel. You can install parakeet via 'git clone https://github.com/PaddlePaddle/Parakeet && cd Parakeet && pip install -e .' and others via pip install
The command '/bin/sh -c hub install deepvoice3_ljspeech==1.0.0' returned a non-zero code: 1
```

**Comment by yt605155624** [comment]
Thanks for your proposal
